routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
// Route::resource('shares', 'ShareController');


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home'); 

    Route::resource('ProfessorClasses', 'V2\ProfessorClassController');
    
    Route::group([
        'prefix' => 'head_study',
        'middleware' => ['auth.admin', 'auth.head_study']
    ], function () {
           
        Route::resource('buildings', 'V2\BuildingController');
        Route::resource('floors', 'V2\FloorController', ['except' => ['create']]);
        Route::get('building/{building_id}/floors/create', 'V2\FloorController@create')->name('floors.create');
        Route::resource('rooms', 'V2\RoomController', ['except' => ['create']]);
        Route::get('floor/{floor_id}/rooms/create', 'V2\RoomController@create')->name('rooms.create');

        Route::get('/buildings/{id}/schedule', 'V2\BuildingScheduleController@index')->name('building.schedule');
        Route::get('/buildings/{id}/schedule/test', 'V2\BuildingScheduleController@test')->name('building.schedule.test');
        Route::get('/buildings/schedule/{time}', 'V2\BuildingScheduleController@filterClasses');
        Route::get('/buildings/schedule/fetchDay', 'V2\BuildingScheduleController@filterDay')->name('day.fetch');
        Route::post('/buildings/schedule/{id}', 'V2\BuildingScheduleController@store')->name('BuildingStoreAssignedClass');

        Route::get('/buildings/{building_id}/room/{room_id}', 'V2\RoomScheduleController@index')->name('ShowRoomSchedule');
        Route::get('/buildings/{building_id}/room/{room_id}/test', 'V2\RoomScheduleController@test');
        Route::get('/buildings/room/schedule/{time}', 'V2\RoomScheduleController@filterClasses');
        Route::post('/buildings/{building_id}/room/schedule/{room_id}', 'V2\RoomScheduleController@store')->name('RoomStoreAssignedClass');
        Route::get('/roomDynamicGroupDependent/fetch', 'V2\RoomScheduleController@filteredDepartmentGroup')->name('roomDynamicGroup.fetch');

        Route::get('/dynamicDepartmentDependent/fetch', 'V2\BuildingScheduleController@filteredFacultyDepartment')->name('dynamicDepartment.fetch');
        Route::get('/dynamicGroupDependent/fetch', 'V2\BuildingScheduleController@filteredDepartmentGroup')->name('dynamicGroup.fetch');
        Route::get('/dynamicSubgroupDependent/fetch', 'V2\BuildingScheduleController@filteredGroupSubgroup')->name('dynamicSubgroup.fetch');
        Route::get('/used_room/filterAvailableRooms', 'V2\UsedRoomController@filterAvailableRooms')->name('used_rooms.index');

        Route::get('/{semester}/{department_id}/{group_id}/download/schedules','V2\DownloadScheduleController@donwloadPdf')->name('download.schedule');
        Route::get('/{building_id}/print/schedules','V2\DownloadScheduleController@index')->name('print.schedule');
        Route::get('/print/schedules','V2\DownloadScheduleController@testing')->name('testing.schedule');

    
        // classes
        Route::get('/index', 'V2\ClassController@index')->name("ShowAllCreateClass");
        Route::get('/create', 'V2\ClassController@create')->name("ClassesCreate");
        Route::post('/store', 'V2\ClassController@store')->name("StoreClassesCreate");
        Route::get('/{id}/edit', 'V2\ClassController@edit')->name("EditClassesCreate");
        Route::post('/update/{id}','V2\ClassController@update')->name("UpdateClassCreate");
        Route::post('/delete/{id}','V2\ClassController@destroy')->name("DeleteClassesCreate");  

        /**
         * add room to use in building 
         * */    
        Route::put('/buildings/{building_id}/add_used_room/{room_id}', 'V2\UsedRoomController@update')->name('AddUseRoom');
        /**
         * add room to use in used room tab
         */
        Route::put('/used_room/addRoomTab', 'V2\UsedRoomController@updateRoom')->name('AddUseRoomTab');

        Route::put('/buildings/{building_id}/delete_used_room/{room_id}', 'V2\UsedRoomController@delete')->name('used_rooms.delete');
        Route::get('/used_room', 'V2\UsedRoomController@index')->name('ShowAllUsedRoom');

        Route::group([
            'prefix' => 'admin',
            'middleware' => ['auth.admin']
        ], function () {
            Route::resource('faculties', 'V2\FacultyController');
            Route::resource('departments', 'V2\DepartmentController');
            Route::resource('subjects', 'V2\SubjectController');
            Route::resource('professors', 'V2\ProfessorController');
            Route::resource('rooms', 'V2\RoomController');
        });
    }); 
});

// Route::group([
//     'prefix' => 'v2',
//     'namespace' => 'V2',
//     'middleware' => ['auth.priority']
// ], function() {

//     Route::get('/home', 'HomeController@index')->name('home');

    // Route::group([
    //     'prefix' => 'classes'
    // ], function () {
    //     Route::get('/', 'ClassController@index')->name("ShowAllCreateClass");
    //     Route::get('/create', 'ClassController@create')->name("ClassesCreate");
    //     Route::post('/store', 'ClassController@store')->name("StoreClassesCreate");
    //     Route::get('/{id}/edit', 'ClassController@edit')->name("EditClassesCreate");
    //     Route::post('/update/{id}','ClassController@update')->name("UpdateClassCreate");
    //     Route::post('/delete/{id}','ClassController@destroy')->name("DeleteClassesCreate");
    
    // });

    // Route::group([
    //     'prefix' => 'controls'
    // ], function () {
    //     //Building
    //     Route::resource('buildings', 'BuildingController');
    //     //Floor
    //     Route::resource('floors', 'FloorController', ['except' => ['create']]);
    //     Route::get('building/{building_id}/floors/create', 'FloorController@create')->name('floors.create');
    //     //Room
    //     Route::resource('rooms', 'RoomController', ['except' => ['create']]);
    //     Route::get('floor/{floor_id}/rooms/create', 'RoomController@create')->name('rooms.create');
    // });

    // Route::group([
    //     'prefix' => 'building-schedules'
    // ], function () {
    //     // schedule for each building 
    //     Route::get('/buildings/{id}/schedule', 'BuildingScheduleController@index')->name('building.schedule');
    //     Route::get('/buildings/{id}/schedule/test', 'BuildingScheduleController@test')->name('building.schedule.test');
    //     Route::get('/buildings/schedule/{time}', 'BuildingScheduleController@filterClasses');
    //     Route::get('/buildings/schedule/fetchDay', 'BuildingScheduleController@filterDay')->name('day.fetch');
    //     Route::post('/buildings/schedule/{id}', 'BuildingScheduleController@store')->name('BuildingStoreAssignedClass');
    // });

    // Route::group([
    //     'prefix' => 'room-schedules'
    // ], function () {
    //     // schedule for each room
    //     Route::get('/buildings/{building_id}/room/{room_id}', 'RoomScheduleController@index')->name('ShowRoomSchedule');
    //     Route::get('/buildings/{building_id}/room/{room_id}/test', 'RoomScheduleController@test');
    //     Route::get('/buildings/room/schedule/{time}', 'RoomScheduleController@filterClasses');
    //     Route::post('/buildings/{building_id}/room/schedule/{room_id}', 'RoomScheduleController@store')->name('RoomStoreAssignedClass');
    //     Route::get('/roomDynamicGroupDependent/fetch', 'RoomScheduleController@filteredDepartmentGroup')->name('roomDynamicGroup.fetch');
    // });

    // Route::group([
    //     'prefix' => 'ajax-fetchs'
    // ], function () {
        
    //     // filter the same group in the department
    //     Route::get('/dynamicDepartmentDependent/fetch', 'BuildingScheduleController@filteredFacultyDepartment')->name('dynamicDepartment.fetch');
    //     Route::get('/dynamicGroupDependent/fetch', 'BuildingScheduleController@filteredDepartmentGroup')->name('dynamicGroup.fetch');
    //     Route::get('/dynamicSubgroupDependent/fetch', 'BuildingScheduleController@filteredGroupSubgroup')->name('dynamicSubgroup.fetch');
    //     Route::get('/used_room/filterAvailableRooms', 'UsedRoomController@filterAvailableRooms')->name('used_rooms.index');
    // });

    // Route::group([
    //     'prefix' => 'download-schedules'
    // ], function () {
  
    //     // Route for download schedule
    //     Route::get('/{semester}/{department_id}/{group_id}/download/schedules','DownloadScheduleController@donwloadPdf')->name('download.schedule');
    //     Route::get('/{building_id}/print/schedules','DownloadScheduleController@index')->name('print.schedule');
    //     Route::get('/print/schedules','DownloadScheduleController@testing')->name('testing.schedule');
    // });

    // Route::group([
    //     'prefix' => 'head-deparment',
    //     'middleware' => ['auth.head_department']
    // ], function () {

    //     // for Classes route
    //     Route::get('/classes', 'ClassController@index')->name("ShowAllCreateClass");
    //     Route::get('/classes/create', 'ClassController@create')->name("ClassesCreate");
    //     Route::post('/classes/store', 'ClassController@store')->name("StoreClassesCreate");
    //     Route::get('/classes/{id}/edit', 'ClassController@edit')->name("EditClassesCreate");
    //     Route::post('/classes/update/{id}','ClassController@update')->name("UpdateClassCreate");
    //     Route::post('/classes/delete/{id}','ClassController@destroy')->name("DeleteClassesCreate");

    //     Route::resource('subjects', 'SubjectController');
    // });

    // Route::group([

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Schedule Homepage') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    {{-- custom style --}}
    {{-- <link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" type="text/css" href="css/main.css"> --}}
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">


    <!-- Bootstrap 4.1.1 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="https://unpkg.com/@coreui/coreui/dist/css/coreui.min.css">
    <!-- Ionicons -->
    {{-- <link rel="stylesheet" href="https://unpkg.com/@coreui/icons/css/coreui-icons.min.css"> --}}
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show" >
    <header class="app-header navbar" style="height: 69px;">
        <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img class="navbar-brand-full" src="http://www.ferupp.com/photos/shares/rupp_logo.png" width="40" height="40" alt="Rupp Logo">
        </a>
        @auth
            <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
                <span class="navbar-toggler-icon"></span>
            </button>
        @endauth
        <ul class="nav navbar-nav ml-auto">
            @guest
                {{-- <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif --}}
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </header>
    
    <div class="app-body">
        @auth
            @include('layouts.sidebar')
        @endauth
        <main class="main">
            @yield('content')
        </main>
    </div>


</body>
<script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://unpkg.com/@coreui/coreui/dist/js/coreui.min.js"></script>
</script>
</html>

resources/views/layouts/menu.blade.php
<li class="nav-item {{ Request::is('buildings*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('home') !!}"><i  class="nav-icon icon-home"></i><span>Home</span></a>
</li>
@can('create', App\User::class)
<li class="nav-item {{ Request::is('buildings*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('buildings.index') !!}"><i class="nav-icon icon-organization"></i><span>Buildings</span></a>
</li>
<li class="nav-item {{ Request::is('classes*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('ShowAllCreateClass') !!}"><i class="nav-icon icon-clock"></i><span>Classes</span></a>
</li>
@endcan
@cannot('create', App\User::class)
<li class="nav-item {{ Request::is('classes*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('ProfessorClasses.index') !!}"><i class="nav-icon icon-clock"></i><span>Professor Classes</span></a>
</li>
@endcannot

@can('create', App\User::class)
<li class="nav-item {{ Request::is('usedRoom*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('ShowAllUsedRoom') !!}"><i class="nav-icon icon-cursor"></i><span>Used Rooms</span></a>
</li> 
@endcan

@can('create', App\User::class)
<li class="nav-item {{ Request::is('department*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('departments.index') !!}"><i class="nav-icon icon-graduation"></i><span>Departments</span></a>
</li>
@endcan

@can('create', App\User::class)
<li class="nav-item {{ Request::is('faculty*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('faculties.index') !!}"><i class="nav-icon icon-layers"></i><span>Faculties</span></a>
</li>
@endcan

@can('create', App\User::class)  
<li class="nav-item {{ Request::is('professor*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('professors.index') !!}"><i class="nav-icon icon-people"></i><span>Professors</span></a>
</li>
@endcan

@can('create', App\User::class)
<li class="nav-item {{ Request::is('subject*') ? 'active' : '' }}">
    <a class="nav-link" href="{!! route('subjects.index') !!}"><i class="nav-icon icon-docs"></i><span>Subjects</span></a>
</li>
@endcan
{{--<li class="nav-item {{ Request::is('rooms*') ? 'active' : '' }}">--}}
{{--    <a class="nav-link" href="{!! route('rooms.index') !!}"><i class="nav-icon icon-cursor"></i><span>Rooms</span></a>--}}
{{--</li>--}}
{{--<li class="nav-item {{ Request::is('floors*') ? 'active' : '' }}">--}}
{{--    <a class="nav-link" href="{!! route('floors.index') !!}"><i class="nav-icon icon-cursor"></i><span>Floors</span></a>--}}
{{--</li>--}}

resources/views/layouts/sidebar.blade.php
<div class="sidebar" style="margin-top: 15px;">
    <nav class="sidebar-nav">
        <ul class="nav">
            @include('layouts.menu')
        </ul>
    </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>