routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
// Route::resource('shares', 'ShareController');


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home'); 

    Route::resource('ProfessorClasses', 'V2\ProfessorClassController');
    
    Route::group([
        'prefix' => 'head_study',
        'middleware' => ['auth.admin', 'auth.head_study']
    ], function () {
           
        Route::resource('buildings', 'V2\BuildingController');
        Route::resource('floors', 'V2\FloorController', ['except' => ['create']]);
        Route::get('building/{building_id}/floors/create', 'V2\FloorController@create')->name('floors.create');
        Route::resource('rooms', 'V2\RoomController', ['except' => ['create']]);
        Route::get('floor/{floor_id}/rooms/create', 'V2\RoomController@create')->name('rooms.create');

        Route::get('/buildings/{id}/schedule', 'V2\BuildingScheduleController@index')->name('building.schedule');
        Route::get('/buildings/{id}/schedule/test', 'V2\BuildingScheduleController@test')->name('building.schedule.test');
        Route::get('/buildings/schedule/{time}', 'V2\BuildingScheduleController@filterClasses');
        Route::get('/buildings/schedule/fetchDay', 'V2\BuildingScheduleController@filterDay')->name('day.fetch');
        Route::post('/buildings/schedule/{id}', 'V2\BuildingScheduleController@store')->name('BuildingStoreAssignedClass');

        Route::get('/buildings/{building_id}/room/{room_id}', 'V2\RoomScheduleController@index')->name('ShowRoomSchedule');
        Route::get('/buildings/{building_id}/room/{room_id}/test', 'V2\RoomScheduleController@test');
        Route::get('/buildings/room/schedule/{time}', 'V2\RoomScheduleController@filterClasses');
        Route::post('/buildings/{building_id}/room/schedule/{room_id}', 'V2\RoomScheduleController@store')->name('RoomStoreAssignedClass');
        Route::get('/roomDynamicGroupDependent/fetch', 'V2\RoomScheduleController@filteredDepartmentGroup')->name('roomDynamicGroup.fetch');

        Route::get('/dynamicDepartmentDependent/fetch', 'V2\BuildingScheduleController@filteredFacultyDepartment')->name('dynamicDepartment.fetch');
        Route::get('/dynamicGroupDependent/fetch', 'V2\BuildingScheduleController@filteredDepartmentGroup')->name('dynamicGroup.fetch');
        Route::get('/dynamicSubgroupDependent/fetch', 'V2\BuildingScheduleController@filteredGroupSubgroup')->name('dynamicSubgroup.fetch');
        Route::get('/used_room/filterAvailableRooms', 'V2\UsedRoomController@filterAvailableRooms')->name('used_rooms.index');

        Route::get('/{semester}/{department_id}/{group_id}/download/schedules','V2\DownloadScheduleController@donwloadPdf')->name('download.schedule');
        Route::get('/{building_id}/print/schedules','V2\DownloadScheduleController@index')->name('print.schedule');
        Route::get('/print/schedules','V2\DownloadScheduleController@testing')->name('testing.schedule');

    
        // classes
        Route::get('/index', 'V2\ClassController@index')->name("ShowAllCreateClass");
        Route::get('/create', 'V2\ClassController@create')->name("ClassesCreate");
        Route::post('/store', 'V2\ClassController@store')->name("StoreClassesCreate");
        Route::get('/{id}/edit', 'V2\ClassController@edit')->name("EditClassesCreate");
        Route::post('/update/{id}','V2\ClassController@update')->name("UpdateClassCreate");
        Route::post('/delete/{id}','V2\ClassController@destroy')->name("DeleteClassesCreate");  

        /**
         * add room to use in building 
         * */    
        Route::put('/buildings/{building_id}/add_used_room/{room_id}', 'V2\UsedRoomController@update')->name('AddUseRoom');
        /**
         * add room to use in used room tab
         */
        Route::put('/used_room/addRoomTab', 'V2\UsedRoomController@updateRoom')->name('AddUseRoomTab');

        Route::put('/buildings/{building_id}/delete_used_room/{room_id}', 'V2\UsedRoomController@delete')->name('used_rooms.delete');
        Route::get('/used_room', 'V2\UsedRoomController@index')->name('ShowAllUsedRoom');

        Route::group([
            'prefix' => 'admin',
            'middleware' => ['auth.admin']
        ], function () {
            Route::resource('faculties', 'V2\FacultyController');
            Route::resource('departments', 'V2\DepartmentController');
            Route::resource('subjects', 'V2\SubjectController');
            Route::resource('professors', 'V2\ProfessorController');
            Route::resource('rooms', 'V2\RoomController');
        });
    }); 
});

// Route::group([
//     'prefix' => 'v2',
//     'namespace' => 'V2',
//     'middleware' => ['auth.priority']
// ], function() {

//     Route::get('/home', 'HomeController@index')->name('home');

    // Route::group([
    //     'prefix' => 'classes'
    // ], function () {
    //     Route::get('/', 'ClassController@index')->name("ShowAllCreateClass");
    //     Route::get('/create', 'ClassController@create')->name("ClassesCreate");
    //     Route::post('/store', 'ClassController@store')->name("StoreClassesCreate");
    //     Route::get('/{id}/edit', 'ClassController@edit')->name("EditClassesCreate");
    //     Route::post('/update/{id}','ClassController@update')->name("UpdateClassCreate");
    //     Route::post('/delete/{id}','ClassController@destroy')->name("DeleteClassesCreate");
    
    // });

    // Route::group([
    //     'prefix' => 'controls'
    // ], function () {
    //     //Building
    //     Route::resource('buildings', 'BuildingController');
    //     //Floor
    //     Route::resource('floors', 'FloorController', ['except' => ['create']]);
    //     Route::get('building/{building_id}/floors/create', 'FloorController@create')->name('floors.create');
    //     //Room
    //     Route::resource('rooms', 'RoomController', ['except' => ['create']]);
    //     Route::get('floor/{floor_id}/rooms/create', 'RoomController@create')->name('rooms.create');
    // });

    // Route::group([
    //     'prefix' => 'building-schedules'
    // ], function () {
    //     // schedule for each building 
    //     Route::get('/buildings/{id}/schedule', 'BuildingScheduleController@index')->name('building.schedule');
    //     Route::get('/buildings/{id}/schedule/test', 'BuildingScheduleController@test')->name('building.schedule.test');
    //     Route::get('/buildings/schedule/{time}', 'BuildingScheduleController@filterClasses');
    //     Route::get('/buildings/schedule/fetchDay', 'BuildingScheduleController@filterDay')->name('day.fetch');
    //     Route::post('/buildings/schedule/{id}', 'BuildingScheduleController@store')->name('BuildingStoreAssignedClass');
    // });

    // Route::group([
    //     'prefix' => 'room-schedules'
    // ], function () {
    //     // schedule for each room
    //     Route::get('/buildings/{building_id}/room/{room_id}', 'RoomScheduleController@index')->name('ShowRoomSchedule');
    //     Route::get('/buildings/{building_id}/room/{room_id}/test', 'RoomScheduleController@test');
    //     Route::get('/buildings/room/schedule/{time}', 'RoomScheduleController@filterClasses');
    //     Route::post('/buildings/{building_id}/room/schedule/{room_id}', 'RoomScheduleController@store')->name('RoomStoreAssignedClass');
    //     Route::get('/roomDynamicGroupDependent/fetch', 'RoomScheduleController@filteredDepartmentGroup')->name('roomDynamicGroup.fetch');
    // });

    // Route::group([
    //     'prefix' => 'ajax-fetchs'
    // ], function () {
        
    //     // filter the same group in the department
    //     Route::get('/dynamicDepartmentDependent/fetch', 'BuildingScheduleController@filteredFacultyDepartment')->name('dynamicDepartment.fetch');
    //     Route::get('/dynamicGroupDependent/fetch', 'BuildingScheduleController@filteredDepartmentGroup')->name('dynamicGroup.fetch');
    //     Route::get('/dynamicSubgroupDependent/fetch', 'BuildingScheduleController@filteredGroupSubgroup')->name('dynamicSubgroup.fetch');
    //     Route::get('/used_room/filterAvailableRooms', 'UsedRoomController@filterAvailableRooms')->name('used_rooms.index');
    // });

    // Route::group([
    //     'prefix' => 'download-schedules'
    // ], function () {
  
    //     // Route for download schedule
    //     Route::get('/{semester}/{department_id}/{group_id}/download/schedules','DownloadScheduleController@donwloadPdf')->name('download.schedule');
    //     Route::get('/{building_id}/print/schedules','DownloadScheduleController@index')->name('print.schedule');
    //     Route::get('/print/schedules','DownloadScheduleController@testing')->name('testing.schedule');
    // });

    // Route::group([
    //     'prefix' => 'head-deparment',
    //     'middleware' => ['auth.head_department']
    // ], function () {

    //     // for Classes route
    //     Route::get('/classes', 'ClassController@index')->name("ShowAllCreateClass");
    //     Route::get('/classes/create', 'ClassController@create')->name("ClassesCreate");
    //     Route::post('/classes/store', 'ClassController@store')->name("StoreClassesCreate");
    //     Route::get('/classes/{id}/edit', 'ClassController@edit')->name("EditClassesCreate");
    //     Route::post('/classes/update/{id}','ClassController@update')->name("UpdateClassCreate");
    //     Route::post('/classes/delete/{id}','ClassController@destroy')->name("DeleteClassesCreate");

    //     Route::resource('subjects', 'SubjectController');
    // });

    // Route::group([

app/Models/Professor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Professor extends Model
{
    protected $fillable = [
        'name'
    ];

    public function departments()
    {
        return $this->belongsToMany('App\Department', 'user_dept', 'user_id', 'department_id');
    }
}

app/Http/Controllers/V2/ProfessorController.php
<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Professor;
use App\User;

class ProfessorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $professors = User::all(); 
        return view('professors.index', compact('professors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('professors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required'
        ]);
        $professor = new Professor([
            'name'=>$request->get('name')
        ]);
        $professor->save();
        return redirect('/professors')->with('success', 'Professor has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $professors = Professor::find($id);
        $prof_dept = $professors->departments;
        return view('professors.show', compact('professors','prof_dept'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $professor = Professor::find($id);
        return view('professors.edit', compact('professor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required'
        ]);

        $professor = Professor::find($id);
        $professor->name = $request->get('name');
        $professor->save();
        return redirect('/professors')->with('success', 'Professor has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $professor = Professor::find($id);
        $professor->delete();
        return redirect('/professors')->with('success', 'Professor has been deleted Successfully');
    }

}

resources/views/professors/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Professor
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('professors.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Professor Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/professors/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Professor
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('professors.update', $professor->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">Professor Name:</label>
          <input type="text" class="form-control" name="name" value={{ $professor->name }} />
        </div>
        
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/professors/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif
  <div>
    <a href="{{ route('professors.create')}}" class="btn btn-primary">Add Professor</a>
  </div>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Professor Name</td>
          <td colspan="3">Actions</td>
          </div>
        </tr>
    </thead>
    <tbody>
        @foreach($professors as $professor)
        <tr>
            <td>{{$professor->id}}</td>
            <td>{{$professor->name}}</td>
            <td><a href="{{ route('professors.edit',$professor->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('professors.destroy', $professor->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
            <td><a href="{{ route('professors.show',$professor->id)}}" class="btn btn-primary">Depts</a></td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/professors/show.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}
    </div><br />
  @endif
  <div class="card-header">
  Professor name: <strong>{{$professors->name}}</strong>
  <br>
  List of Departments
  </div>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Department Name</td>
        </tr>
    </thead>
    <tbody>
      @foreach($prof_dept as $department)
        <tr>
            <td>{{$department->id}}</td>
            <td>{{$department->name}}</td>
        </tr>
      @endforeach
    </tbody>
  </table>
<div>
@endsection